### ISSUE TITLE
Error occurred when executing KSampler //Inspire:

### ISSUE THREAD

**Issue by lesteryebin** [ltdrdata/ComfyUI-Inspire-Pack#137] opened 2024-08-05 03:59 UTC
Error occurred when executing KSampler //Inspire:

Boolean value of Tensor with more than one value is ambiguous

File "E:\ComfyUI-aki-v1.3\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "E:\ComfyUI-aki-v1.3\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "E:\ComfyUI-aki-v1.3\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Inspire-Pack\inspire\a1111_compat.py", line 135, in doit
return (inspire_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise, noise_mode,
File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Inspire-Pack\inspire\a1111_compat.py", line 96, in inspire_ksampler
raise e
File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Inspire-Pack\inspire\a1111_compat.py", line 84, in inspire_ksampler
samples = common.impact_sampling(
File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Inspire-Pack\inspire\libs\common.py", line 14, in impact_sampling
return nodes.NODE_CLASS_MAPPINGS['RegionalSampler'].separated_sample(*args, **kwargs)
File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack\modules\impact\special_samplers.py", line 408, in separated_sample
return separated_sample(*args, **kwargs)
File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_sampling.py", line 202, in separated_sample
res = sample_with_custom_noise(model, add_noise, seed, cfg, positive, negative, impact_sampler, sigmas, latent_image, noise=noise, callback=callback)
File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_sampling.py", line 154, in sample_with_custom_noise
samples = guider.sample(noise, latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=touched_callback, disable_pbar=disable_pbar, seed=noise_seed)
File "E:\ComfyUI-aki-v1.3\comfy\samplers.py", line 716, in sample
output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
File "E:\ComfyUI-aki-v1.3\comfy\samplers.py", line 695, in inner_sample
samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
File "E:\ComfyUI-aki-v1.3\comfy\samplers.py", line 600, in sample
samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_sampling.py", line 52, in sample_dpmpp_sde
return k_diffusion_sampling.sample_dpmpp_sde(model, x, sigmas, **kwargs)
File "E:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "E:\ComfyUI-aki-v1.3\comfy\k_diffusion\sampling.py", line 579, in sample_dpmpp_sde
denoised_2 = model(x_2, sigma_fn(s) * s_in, **extra_args)
File "E:\ComfyUI-aki-v1.3\comfy\samplers.py", line 299, in __call__
out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
File "E:\ComfyUI-aki-v1.3\comfy\samplers.py", line 682, in __call__
return self.predict_noise(*args, **kwargs)
File "E:\ComfyUI-aki-v1.3\comfy\samplers.py", line 685, in predict_noise
return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-AutomaticCFG\nodes.py", line 52, in sampling_function_patched
out = comfy.samplers.calc_cond_batch(model, conds, x, timestep, model_options)
File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-TiledDiffusion\.patches.py", line 89, in calc_cond_batch
output = model_options['model_function_wrapper'](model.apply_model, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
File "E:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-TiledDiffusion\tiled_diffusion.py", line 547, in __call__
self.process_controlnet(x_tile.shape, x_tile.dtype, c_in, cond_or_uncond, bboxes, N, batch_id)
File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-TiledDiffusion\tiled_diffusion.py", line 306, in process_controlnet
while len(self.control_params[tuple_key][param_id]) <= batch_id:
File "E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 38, in wrapper_len
if real_length > 0 and type(cond_or_uncond) == list and (cond_or_uncond[0] in [0, 1]):

**Comment by ltdrdata** [comment] 2024-08-05 14:55
Your error is occurring through multiple custom nodes, making it difficult to precisely identify the problem.
The final point of occurrence is ComfyUI-Advanced-ControlNet, but ComfyUI-TiledDiffusion could also be the cause. Narrow down the scope of the problem by removing unnecessary nodes.

The first thing to do is to check if the problem occurs when using a regular KSampler instead of KSampler //Inspire.

**Comment by godsgo** [comment] 2024-08-05 15:51
Hello, thank you for the well done job, but with the latest update a similar error began to appear. What can I do to fix my workflow? 
[error.json](https://github.com/user-attachments/files/16499908/error.json)

**Error occurred when executing KSampler //Inspire:
Boolean value of Tensor with more than one value is ambiguous**
![Без имени-2](https://github.com/user-attachments/assets/d1273488-4b06-4332-8274-8bd7d23e0164)

Workflow work well without [TiledDiffusion](https://github.com/shiimizu/ComfyUI-TiledDiffusion)
![2334534534](https://github.com/user-attachments/assets/0511bb0a-1c10-4a9b-b2ab-df7de9bad97e)
thank you in advance

**Comment by ltdrdata** [comment] 2024-08-05 16:20
![image](https://github.com/user-attachments/assets/d44f02de-3616-49a3-8916-779a767fe2c9)

I cannot reproduce that issue.
Make sure your ComfyUI and TiledDiffusion node is up to date.

**Comment by KINGLIFER** [comment] 2024-08-06 02:11
Same here. Updated>Error occurred when executing KSampler //Inspire:

Boolean value of Tensor with more than one value is ambiguous

**Comment by ltdrdata** [comment] 2024-08-06 05:11
> Same here. Updated>Error occurred when executing KSampler //Inspire:
> 
> Boolean value of Tensor with more than one value is ambiguous

What is the version of ComfyUI-Advanced-ControlNet.

**Comment by wardensc2** [comment] 2024-08-06 12:54
Here is the workflow sample that Original Ksample working but not your Inspire Ksample. Please check, thank in advance. 
[workflow sample.json](https://github.com/user-attachments/files/16510513/workflow.sample.json)

**Comment by ltdrdata** [comment] 2024-08-06 13:45
> Here is the workflow sample that Original Ksample working but not your Inspire Ksample. Please check, thank in advance. [workflow sample.json](https://github.com/user-attachments/files/16510513/workflow.sample.json)
![tiled_diffusion_advanced_controlnet](https://github.com/user-attachments/assets/7bc1ae4a-f7d5-466c-8f6a-cdeb0d2e2e4f)

I've narrowed down the scope of the issue.

This issue is not related to `KSampler //Inspire`.
It's an issue where `TiledDiffusion` and `Advanced-ControlNet`, when combined, do not properly support `SamplerCustomAdvanced`.


This issue should be transferred to the above two nodes.

**Closed by ltdrdata** 2024-08-06 13:45 UTC

**Comment by ltdrdata** [comment] 2024-08-06 16:58
This issue arose because Advanced ControlNet currently doesn't support SamplerCustomAdvanced.
For the time being, we've patched it to operate as closely as possible to the existing method for compatibility.

Update Impact Pack to latest version.
